class Directories:
    COLLECTION_DIR = "collection/"
    ISSUE_DIR = "issue/"
    COLUMN_FIELD_DIR = "var/column-field/"
    TRANSFORMED_DIR = "transformed/"
    FLATTENED_DIR = "flattened/"
    CONVERTED_DIR = "converted/"
    DATASET_DIR = "dataset/"
    PIPELINE_DIR = "pipeline/"
    SPECIFICATION_DIR = "specification/"
    DATASET_RESOURCE_DIR = "var/dataset-resource/"
