article-4-direction:
- reference
- name
- description
- document-url
- documentation-url
article-4-direction-area:
- reference
- geometry
- name
- permitted-development-rights
conservation-area:
- reference
- geometry
- name
conservation-area-document:
- reference
- name
- conservation-area
- document-url
- documentation-url
- document-type
tree-preservation-order:
- reference
- name
- document-url
- documentation-url
tree-preservation-zone:
- reference
- geometry
listed-building-outline:
- reference
- geometry
- name
- listed-building
tree:
- reference
-
  - point
  - geometry
