article-4-direction:
- reference
article-4-direction-area:
- reference
- geometry
- name
- permitted-development-rights
conservation-area:
- reference
- geometry
- name
tree-preservation-zone:
- reference
- geometry
listed-building-outline:
- reference
- geometry
- name
- listed-building
tree:
- reference
-
  - point
  - geometry
