mappings:
- field: documentation-url
  issue-type: invalid URI
  description: Documentation URL must be a real URL
  summary-singular: "1 documentation URL must be a real URL"
  summary-plural: "{count} documentation URLs must be a real URL"
- field: document-url
  issue-type: invalid URI
  description: Document URL must be a real URL
  summary-singular: "1 document URL must be a real URL"
  summary-plural: "{count} document URLs must be a real URL"
- field: start-date
  issue-type: invalid date
  description: Start date must be a real date
  summary-singular: "1 start date must be a real date"
  summary-plural: "{count} start dates must be a real date"
- field: entry-date
  issue-type: invalid date
  description: Entry date must be a real date
  summary-singular: "1 entry date must be a real date"
  summary-plural: "{count} entry dates must be a real date"
- field: end-date
  issue-type: invalid date
  description: End date must be a real date
  summary-singular: "1 end date must be a real date"
  summary-plural: "{count} end dates must be a real date"
- field: geometry
  issue-type: OSGB out of bounds of England
  description: Geometry must be in England
  summary-singular: "1 geometry must be in England"
  summary-plural: "{count} geometries must be in England"
- field: geometry
  issue-type: Unexpected geom type
  description: Geometry must be a point or polygon
  summary-singular: "1 geometry must be a point or polygon"
  summary-plural: "{count} geometries must be a point or polygon"
- field: geometry
  issue-type: Unexpected geom type within GeometryCollection
  description: Geometry must be a polygon
  summary-singular: "1 geometry must be a polygon"
  summary-plural: "{count} geometries must be a polygon"
- field: geometry
  issue-type: WGS84 out of bounds
  description: Geometry must be in England
  summary-singular: "1 geometry must be in England"
  summary-plural: "{count} geometries must be in England"
- field: geometry
  issue-type: WGS84 out of bounds of England
  description: Geometry must be in England
  summary-singular: "1 geometry must be in England"
  summary-plural: "{count} geometries must be in England"
- field: geometry
  issue-type: invalid WKT
  description: Geometry must be in Well-Known Text (WKT) format
  summary-singular: "1 geometry must be in Well-Known Text (WKT) format"
  summary-plural: "{count} geometries must be in Well-Known Text (WKT) format"
- field: geometry
  issue-type: invalid coordinates
  description: Geometry must use WGS84, OSGB or Mercator coordinates
  summary-singular: "1 geometry must use WGS84, OSGB or Mercator coordinates"
  summary-plural: "{count} geometries must use WGS84, OSGB or Mercator coordinates"
- field: geometry
  issue-type: invalid geometry - not fixable
  description: Geometry must be correctly formatted
  summary-singular: "1 geometry must be correctly formatted"
  summary-plural: "{count} geometries must be correctly formatted"
- field: entry-date
  issue-type: future entry-date
  description: Entry date must be today or in the past
  summary-singular: "1 entry date must be today or in the past"
  summary-plural: "{count} entry dates must be today or in the past"
